
package com.carlos.avisamedelcocheclientews.clienteWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AvisameDelCocheWSService", targetNamespace = "http://avisamedelcochews.carlos.com/", wsdlLocation = "file:/C:/Users/Carlos/Documents/Proyectos/avisamedelcoche/dev/AvisameDelCocheClienteWS/src/wsdl/AvisameDelCocheWSService.wsdl")
public class AvisameDelCocheWSService
    extends Service
{

    private final static URL AVISAMEDELCOCHEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException AVISAMEDELCOCHEWSSERVICE_EXCEPTION;
    private final static QName AVISAMEDELCOCHEWSSERVICE_QNAME = new QName("http://avisamedelcochews.carlos.com/", "AvisameDelCocheWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Carlos/Documents/Proyectos/avisamedelcoche/dev/AvisameDelCocheClienteWS/src/wsdl/AvisameDelCocheWSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AVISAMEDELCOCHEWSSERVICE_WSDL_LOCATION = url;
        AVISAMEDELCOCHEWSSERVICE_EXCEPTION = e;
    }

    public AvisameDelCocheWSService() {
        super(__getWsdlLocation(), AVISAMEDELCOCHEWSSERVICE_QNAME);
    }

    public AvisameDelCocheWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AVISAMEDELCOCHEWSSERVICE_QNAME, features);
    }

    public AvisameDelCocheWSService(URL wsdlLocation) {
        super(wsdlLocation, AVISAMEDELCOCHEWSSERVICE_QNAME);
    }

    public AvisameDelCocheWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AVISAMEDELCOCHEWSSERVICE_QNAME, features);
    }

    public AvisameDelCocheWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AvisameDelCocheWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AvisameDelCocheWS
     */
    @WebEndpoint(name = "AvisameDelCocheWSPort")
    public AvisameDelCocheWS getAvisameDelCocheWSPort() {
        return super.getPort(new QName("http://avisamedelcochews.carlos.com/", "AvisameDelCocheWSPort"), AvisameDelCocheWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AvisameDelCocheWS
     */
    @WebEndpoint(name = "AvisameDelCocheWSPort")
    public AvisameDelCocheWS getAvisameDelCocheWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://avisamedelcochews.carlos.com/", "AvisameDelCocheWSPort"), AvisameDelCocheWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AVISAMEDELCOCHEWSSERVICE_EXCEPTION!= null) {
            throw AVISAMEDELCOCHEWSSERVICE_EXCEPTION;
        }
        return AVISAMEDELCOCHEWSSERVICE_WSDL_LOCATION;
    }

}
