CREATE TABLE `componente` (
  `ID_COMPONENTE` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  `KILOMETROS_DURACION` int(11) NOT NULL,
  PRIMARY KEY (`ID_COMPONENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;